name: Atividade 02.3 - Utilizando variáveis

on:
  push:

env:
  CURSO: "Integração Contínua"

jobs:
  mostrar-variaveis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Exibir nome do curso
        run: echo "Curso $CURSO"

      - name: Exibir usuário que executou o workflow
        run: echo "${{ github.actor }}"

      - name: Exibir nome do repositório
        run: echo "${{ github.repository }}"

      - name: Exibir branch utilizada
        run: echo "${{ github.ref_name }}"