name: Atividade 02.1 - Workflow funcional

on:
  push:

jobs:
  primeiro-job:
    runs-on: ubuntu-latest
    steps:
      - name: Primeiro passo
        run: echo "Primeiro passo"

      - name: Checkout
        uses: actions/checkout@v5

      - name: Lista arquivos
        run: ls ${{ github.workspace }}

      - name: Status
        run: echo "Status ${{ job.status }}."
